// Class: ReadMLPBNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBNN
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 11:30:04 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "True" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar                                            'F'    [-99,0.999695241451]
f_angle_costheta1             f_angle_costheta1             f_angle_costheta1             f_angle_costheta1                                               'F'    [-99,0.999956786633]
f_angle_costheta2             f_angle_costheta2             f_angle_costheta2             f_angle_costheta2                                               'F'    [-99,0.999614596367]
f_angle_phi                   f_angle_phi                   f_angle_phi                   f_angle_phi                                                     'F'    [-99,3.1414334774]
f_angle_phistar1              f_angle_phistar1              f_angle_phistar1              f_angle_phistar1                                                'F'    [-99,3.14026069641]
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.3993835449,117.858093262]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0253534317,114.000205994]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBNN : public IClassifierReader {

 public:

   // constructor
   ReadMLPBNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBNN" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_angle_costhetastar", "f_angle_costheta1", "f_angle_costheta2", "f_angle_phi", "f_angle_phistar1", "f_Z1mass", "f_Z2mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBNN::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.178177126749891;
   fWeightMatrix0to1[1][0] = 1.57437119119755;
   fWeightMatrix0to1[2][0] = 1.52405665693028;
   fWeightMatrix0to1[3][0] = 1.52283204378017;
   fWeightMatrix0to1[4][0] = -1.49818440703908;
   fWeightMatrix0to1[5][0] = -1.05107735540767;
   fWeightMatrix0to1[6][0] = -0.832246136468028;
   fWeightMatrix0to1[7][0] = 1.60732126908259;
   fWeightMatrix0to1[8][0] = -1.15337313649449;
   fWeightMatrix0to1[9][0] = -0.889206699975;
   fWeightMatrix0to1[10][0] = -1.6955289277986;
   fWeightMatrix0to1[11][0] = -0.483008768571817;
   fWeightMatrix0to1[0][1] = -0.865047486913068;
   fWeightMatrix0to1[1][1] = -1.48313623509314;
   fWeightMatrix0to1[2][1] = -0.875371343082786;
   fWeightMatrix0to1[3][1] = 0.581802671445886;
   fWeightMatrix0to1[4][1] = -0.19139259551334;
   fWeightMatrix0to1[5][1] = 2.10892747454653;
   fWeightMatrix0to1[6][1] = 0.21594851194593;
   fWeightMatrix0to1[7][1] = 0.973253355160972;
   fWeightMatrix0to1[8][1] = 0.189439192964276;
   fWeightMatrix0to1[9][1] = -0.560226579955527;
   fWeightMatrix0to1[10][1] = 0.190835238730105;
   fWeightMatrix0to1[11][1] = -0.0023421048118327;
   fWeightMatrix0to1[0][2] = -0.737498290893549;
   fWeightMatrix0to1[1][2] = -1.14811381171577;
   fWeightMatrix0to1[2][2] = 0.677967040880518;
   fWeightMatrix0to1[3][2] = -0.649396612531167;
   fWeightMatrix0to1[4][2] = -1.18751816384562;
   fWeightMatrix0to1[5][2] = 0.189389113575486;
   fWeightMatrix0to1[6][2] = 0.248128451462931;
   fWeightMatrix0to1[7][2] = 1.10699700849643;
   fWeightMatrix0to1[8][2] = 0.295954018990696;
   fWeightMatrix0to1[9][2] = -0.136607894280235;
   fWeightMatrix0to1[10][2] = -0.127552221691533;
   fWeightMatrix0to1[11][2] = -0.0412819286876806;
   fWeightMatrix0to1[0][3] = -0.996434900020372;
   fWeightMatrix0to1[1][3] = 1.14552638018114;
   fWeightMatrix0to1[2][3] = -1.78456390453518;
   fWeightMatrix0to1[3][3] = 0.915257069989008;
   fWeightMatrix0to1[4][3] = 1.01221588576957;
   fWeightMatrix0to1[5][3] = 0.568026008878431;
   fWeightMatrix0to1[6][3] = 1.01856112331577;
   fWeightMatrix0to1[7][3] = 0.857363077102168;
   fWeightMatrix0to1[8][3] = -0.570706684382259;
   fWeightMatrix0to1[9][3] = -1.2312123708163;
   fWeightMatrix0to1[10][3] = 0.296821244786858;
   fWeightMatrix0to1[11][3] = -0.200078090291716;
   fWeightMatrix0to1[0][4] = 1.16830284563245;
   fWeightMatrix0to1[1][4] = 0.497416050891796;
   fWeightMatrix0to1[2][4] = 0.873686587633662;
   fWeightMatrix0to1[3][4] = 1.06150041619318;
   fWeightMatrix0to1[4][4] = -1.09635653000697;
   fWeightMatrix0to1[5][4] = 0.363844920451828;
   fWeightMatrix0to1[6][4] = -1.51310272500248;
   fWeightMatrix0to1[7][4] = -0.708243242365876;
   fWeightMatrix0to1[8][4] = -0.736130602554857;
   fWeightMatrix0to1[9][4] = -1.33386269701677;
   fWeightMatrix0to1[10][4] = 0.772643468986563;
   fWeightMatrix0to1[11][4] = 0.638219945099066;
   fWeightMatrix0to1[0][5] = -1.47552493315176;
   fWeightMatrix0to1[1][5] = -0.285948461321161;
   fWeightMatrix0to1[2][5] = 0.57839999250781;
   fWeightMatrix0to1[3][5] = 0.345149276044329;
   fWeightMatrix0to1[4][5] = 1.56615201691203;
   fWeightMatrix0to1[5][5] = -1.49810733025817;
   fWeightMatrix0to1[6][5] = 0.082676748203495;
   fWeightMatrix0to1[7][5] = -0.688206605480796;
   fWeightMatrix0to1[8][5] = 1.13439491635051;
   fWeightMatrix0to1[9][5] = -0.490366260731391;
   fWeightMatrix0to1[10][5] = -0.0928109921546212;
   fWeightMatrix0to1[11][5] = -1.26781364737756;
   fWeightMatrix0to1[0][6] = 1.56684296058281;
   fWeightMatrix0to1[1][6] = -0.104683406941333;
   fWeightMatrix0to1[2][6] = 0.221194221012866;
   fWeightMatrix0to1[3][6] = -0.338220900948267;
   fWeightMatrix0to1[4][6] = -1.28693167978631;
   fWeightMatrix0to1[5][6] = -3.02676900506085;
   fWeightMatrix0to1[6][6] = 1.30981691279253;
   fWeightMatrix0to1[7][6] = 0.378145903016677;
   fWeightMatrix0to1[8][6] = 2.02363791101635;
   fWeightMatrix0to1[9][6] = 0.469575614246695;
   fWeightMatrix0to1[10][6] = 0.742197431610252;
   fWeightMatrix0to1[11][6] = -1.39508052225385;
   fWeightMatrix0to1[0][7] = -1.0634331014888;
   fWeightMatrix0to1[1][7] = 0.216979873374839;
   fWeightMatrix0to1[2][7] = 0.702290266981085;
   fWeightMatrix0to1[3][7] = -0.743052017578365;
   fWeightMatrix0to1[4][7] = -2.21295254122441;
   fWeightMatrix0to1[5][7] = -1.7653905422244;
   fWeightMatrix0to1[6][7] = -0.508506732515578;
   fWeightMatrix0to1[7][7] = -0.13176032862282;
   fWeightMatrix0to1[8][7] = 1.28755392843703;
   fWeightMatrix0to1[9][7] = -1.22305501739614;
   fWeightMatrix0to1[10][7] = -1.31841025413294;
   fWeightMatrix0to1[11][7] = 1.42616440692478;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.50738948071089;
   fWeightMatrix1to2[0][1] = -1.20585817258271;
   fWeightMatrix1to2[0][2] = -0.932357380666146;
   fWeightMatrix1to2[0][3] = -0.398670654688642;
   fWeightMatrix1to2[0][4] = -1.32202156745463;
   fWeightMatrix1to2[0][5] = -1.30255278131855;
   fWeightMatrix1to2[0][6] = 0.379220983111819;
   fWeightMatrix1to2[0][7] = 0.489753401206032;
   fWeightMatrix1to2[0][8] = -1.91175931282559;
   fWeightMatrix1to2[0][9] = 1.78231823410982;
   fWeightMatrix1to2[0][10] = -0.6592131444139;
   fWeightMatrix1to2[0][11] = -0.893447930607939;
   fWeightMatrix1to2[0][12] = 0.708685913393236;
}

inline double ReadMLPBNN::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBNN::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBNN::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBNN::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -99;
   fMax_1[0][0] = 0.998964726925;
   fMin_1[1][0] = -99;
   fMax_1[1][0] = 0.999695241451;
   fMin_1[2][0] = -99;
   fMax_1[2][0] = 0.999695241451;
   fMin_1[0][1] = -99;
   fMax_1[0][1] = 0.999956786633;
   fMin_1[1][1] = -99;
   fMax_1[1][1] = 0.999882161617;
   fMin_1[2][1] = -99;
   fMax_1[2][1] = 0.999956786633;
   fMin_1[0][2] = -99;
   fMax_1[0][2] = 0.999560713768;
   fMin_1[1][2] = -99;
   fMax_1[1][2] = 0.999614596367;
   fMin_1[2][2] = -99;
   fMax_1[2][2] = 0.999614596367;
   fMin_1[0][3] = -99;
   fMax_1[0][3] = 3.14135980606;
   fMin_1[1][3] = -99;
   fMax_1[1][3] = 3.1414334774;
   fMin_1[2][3] = -99;
   fMax_1[2][3] = 3.1414334774;
   fMin_1[0][4] = -99;
   fMax_1[0][4] = 3.14026069641;
   fMin_1[1][4] = -99;
   fMax_1[1][4] = 3.13832426071;
   fMin_1[2][4] = -99;
   fMax_1[2][4] = 3.14026069641;
   fMin_1[0][5] = 40.8050003052;
   fMax_1[0][5] = 117.858093262;
   fMin_1[1][5] = 40.3993835449;
   fMax_1[1][5] = 113.862014771;
   fMin_1[2][5] = 40.3993835449;
   fMax_1[2][5] = 117.858093262;
   fMin_1[0][6] = 12.0253534317;
   fMax_1[0][6] = 114.000205994;
   fMin_1[1][6] = 12.0306968689;
   fMax_1[1][6] = 108.812988281;
   fMin_1[2][6] = 12.0253534317;
   fMax_1[2][6] = 114.000205994;
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
