// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 16:08:46 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 5950
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.7789421082,117.858093262]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0253534317,114.000205994]
f_pt4l                        f_pt4l                        f_pt4l                        f_pt4l                                                          'F'    [-99,822.938476562]
f_massjj                      f_massjj                      f_massjj                      f_massjj                                                        'F'    [27.9619979858,4060.77124023]
f_deltajj                     f_deltajj                     f_deltajj                     f_deltajj                                                       'F'    [0.00134062767029,8.83846282959]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_Z1mass", "f_Z2mass", "f_pt4l", "f_massjj", "f_deltajj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.518183118397251;
   fWeightMatrix0to1[1][0] = 0.511671095041973;
   fWeightMatrix0to1[2][0] = 0.0646254106003118;
   fWeightMatrix0to1[3][0] = 1.34803144407338;
   fWeightMatrix0to1[4][0] = -1.97583286901997;
   fWeightMatrix0to1[5][0] = -0.107664236605143;
   fWeightMatrix0to1[6][0] = -0.396665196308389;
   fWeightMatrix0to1[7][0] = 1.79315621316228;
   fWeightMatrix0to1[8][0] = -0.187879291115275;
   fWeightMatrix0to1[9][0] = -0.252085647906045;
   fWeightMatrix0to1[0][1] = -1.17560038290087;
   fWeightMatrix0to1[1][1] = 0.568195813230906;
   fWeightMatrix0to1[2][1] = 0.0366936058352581;
   fWeightMatrix0to1[3][1] = 0.316407008233782;
   fWeightMatrix0to1[4][1] = -2.5369652693632;
   fWeightMatrix0to1[5][1] = -0.240465281441822;
   fWeightMatrix0to1[6][1] = -0.373266807138433;
   fWeightMatrix0to1[7][1] = 2.41156884596955;
   fWeightMatrix0to1[8][1] = 0.110101275485067;
   fWeightMatrix0to1[9][1] = 0.473070722448238;
   fWeightMatrix0to1[0][2] = -0.184470537232725;
   fWeightMatrix0to1[1][2] = 0.0279104456165733;
   fWeightMatrix0to1[2][2] = -0.814257019587112;
   fWeightMatrix0to1[3][2] = 1.43459212881719;
   fWeightMatrix0to1[4][2] = -0.165164716674981;
   fWeightMatrix0to1[5][2] = 0.906388734807982;
   fWeightMatrix0to1[6][2] = 1.09909610109783;
   fWeightMatrix0to1[7][2] = -0.586622250424791;
   fWeightMatrix0to1[8][2] = -1.86263828261327;
   fWeightMatrix0to1[9][2] = 0.332217600834224;
   fWeightMatrix0to1[0][3] = 0.442911424191038;
   fWeightMatrix0to1[1][3] = 2.51702768109797;
   fWeightMatrix0to1[2][3] = -2.37468523109277;
   fWeightMatrix0to1[3][3] = 0.394885276221759;
   fWeightMatrix0to1[4][3] = 0.658921055547413;
   fWeightMatrix0to1[5][3] = -2.58031568151437;
   fWeightMatrix0to1[6][3] = -1.71562058808182;
   fWeightMatrix0to1[7][3] = 0.648898970961373;
   fWeightMatrix0to1[8][3] = -1.63391911122278;
   fWeightMatrix0to1[9][3] = 0.526069062334256;
   fWeightMatrix0to1[0][4] = -0.0124720469393034;
   fWeightMatrix0to1[1][4] = -0.368599298113121;
   fWeightMatrix0to1[2][4] = 1.53667560326827;
   fWeightMatrix0to1[3][4] = 0.542070584091816;
   fWeightMatrix0to1[4][4] = -0.450142591350446;
   fWeightMatrix0to1[5][4] = -1.86356154405363;
   fWeightMatrix0to1[6][4] = 0.453287706294721;
   fWeightMatrix0to1[7][4] = -0.519138625818088;
   fWeightMatrix0to1[8][4] = -0.164727908416175;
   fWeightMatrix0to1[9][4] = 0.0682945511753097;
   fWeightMatrix0to1[0][5] = -0.00706903492918115;
   fWeightMatrix0to1[1][5] = 2.19614799031408;
   fWeightMatrix0to1[2][5] = -2.89232145237085;
   fWeightMatrix0to1[3][5] = 1.1949442817811;
   fWeightMatrix0to1[4][5] = -1.07502522557271;
   fWeightMatrix0to1[5][5] = -2.37167200655562;
   fWeightMatrix0to1[6][5] = -0.471288079692057;
   fWeightMatrix0to1[7][5] = -1.96244872715625;
   fWeightMatrix0to1[8][5] = -1.3280597202248;
   fWeightMatrix0to1[9][5] = 0.991308504743495;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.402201573969853;
   fWeightMatrix1to2[0][1] = -0.0823219584606315;
   fWeightMatrix1to2[0][2] = -0.872571221414712;
   fWeightMatrix1to2[0][3] = 0.34742344677358;
   fWeightMatrix1to2[0][4] = 0.331720592071327;
   fWeightMatrix1to2[0][5] = -0.50453042445527;
   fWeightMatrix1to2[0][6] = -0.181909749061552;
   fWeightMatrix1to2[0][7] = -0.434567359054762;
   fWeightMatrix1to2[0][8] = 0.440175008471343;
   fWeightMatrix1to2[0][9] = 0.152271283926932;
   fWeightMatrix1to2[0][10] = -0.754756251283055;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 42.0261077881;
   fMax_1[0][0] = 117.858093262;
   fMin_1[1][0] = 40.7789421082;
   fMax_1[1][0] = 115.629348755;
   fMin_1[2][0] = 40.7789421082;
   fMax_1[2][0] = 117.858093262;
   fMin_1[0][1] = 12.0253534317;
   fMax_1[0][1] = 114.000205994;
   fMin_1[1][1] = 12.0355405807;
   fMax_1[1][1] = 104.822761536;
   fMin_1[2][1] = 12.0253534317;
   fMax_1[2][1] = 114.000205994;
   fMin_1[0][2] = -99;
   fMax_1[0][2] = 822.938476562;
   fMin_1[1][2] = -99;
   fMax_1[1][2] = 657.168334961;
   fMin_1[2][2] = -99;
   fMax_1[2][2] = 822.938476562;
   fMin_1[0][3] = 27.9619979858;
   fMax_1[0][3] = 4060.77124023;
   fMin_1[1][3] = 28.7857055664;
   fMax_1[1][3] = 2549.00561523;
   fMin_1[2][3] = 27.9619979858;
   fMax_1[2][3] = 4060.77124023;
   fMin_1[0][4] = 0.00819897651672;
   fMax_1[0][4] = 8.83846282959;
   fMin_1[1][4] = 0.00134062767029;
   fMax_1[1][4] = 8.04142284393;
   fMin_1[2][4] = 0.00134062767029;
   fMax_1[2][4] = 8.83846282959;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
