// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 11:48:26 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar                                            'F'    [-99,0.999695241451]
f_angle_costheta1             f_angle_costheta1             f_angle_costheta1             f_angle_costheta1                                               'F'    [-99,0.999956786633]
f_angle_costheta2             f_angle_costheta2             f_angle_costheta2             f_angle_costheta2                                               'F'    [-99,0.999614596367]
f_angle_phi                   f_angle_phi                   f_angle_phi                   f_angle_phi                                                     'F'    [-99,3.1414334774]
f_angle_phistar1              f_angle_phistar1              f_angle_phistar1              f_angle_phistar1                                                'F'    [-99,3.14026069641]
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.3993835449,117.858093262]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0253534317,114.000205994]
f_pt4l                        f_pt4l                        f_pt4l                        f_pt4l                                                          'F'    [-99,822.938476562]
f_eta4l                       f_eta4l                       f_eta4l                       f_eta4l                                                         'F'    [-99,6.83502864838]
f_massjj                      f_massjj                      f_massjj                      f_massjj                                                        'F'    [-999,4060.77124023]
f_deltajj                     f_deltajj                     f_deltajj                     f_deltajj                                                       'F'    [-999,8.83846282959]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_angle_costhetastar", "f_angle_costheta1", "f_angle_costheta2", "f_angle_phi", "f_angle_phistar1", "f_Z1mass", "f_Z2mass", "f_pt4l", "f_eta4l", "f_massjj", "f_deltajj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.0564779010427828;
   fWeightMatrix0to1[1][0] = 1.83025056333026;
   fWeightMatrix0to1[2][0] = 0.216385020878504;
   fWeightMatrix0to1[3][0] = 1.81937185576668;
   fWeightMatrix0to1[4][0] = -2.07737835570575;
   fWeightMatrix0to1[5][0] = -2.1130783939677;
   fWeightMatrix0to1[6][0] = -0.998219567352888;
   fWeightMatrix0to1[7][0] = 2.18923525129604;
   fWeightMatrix0to1[8][0] = -1.49172987998265;
   fWeightMatrix0to1[9][0] = -0.568814102235619;
   fWeightMatrix0to1[10][0] = -1.69237653925866;
   fWeightMatrix0to1[11][0] = 0.0779420568493328;
   fWeightMatrix0to1[12][0] = -1.2168234478161;
   fWeightMatrix0to1[13][0] = -0.627979492917824;
   fWeightMatrix0to1[14][0] = -0.901771183367793;
   fWeightMatrix0to1[15][0] = 0.0290041652161411;
   fWeightMatrix0to1[0][1] = -0.011049318571992;
   fWeightMatrix0to1[1][1] = 1.7642872250174;
   fWeightMatrix0to1[2][1] = -0.453931583814106;
   fWeightMatrix0to1[3][1] = 0.647163154533885;
   fWeightMatrix0to1[4][1] = -0.429814599622238;
   fWeightMatrix0to1[5][1] = -1.77897944773703;
   fWeightMatrix0to1[6][1] = 0.66807707777239;
   fWeightMatrix0to1[7][1] = 0.474694723382301;
   fWeightMatrix0to1[8][1] = -1.44980604526851;
   fWeightMatrix0to1[9][1] = 0.289751491072879;
   fWeightMatrix0to1[10][1] = 1.45086681102651;
   fWeightMatrix0to1[11][1] = -0.587385079251728;
   fWeightMatrix0to1[12][1] = -1.85231229430565;
   fWeightMatrix0to1[13][1] = 0.4617701859895;
   fWeightMatrix0to1[14][1] = 1.43347928699986;
   fWeightMatrix0to1[15][1] = 1.25923529370605;
   fWeightMatrix0to1[0][2] = 0.0762173598481605;
   fWeightMatrix0to1[1][2] = 0.37131171505063;
   fWeightMatrix0to1[2][2] = -0.30280289893157;
   fWeightMatrix0to1[3][2] = -0.479181178840389;
   fWeightMatrix0to1[4][2] = -1.53122808099713;
   fWeightMatrix0to1[5][2] = 0.212116397262172;
   fWeightMatrix0to1[6][2] = -1.02348832727999;
   fWeightMatrix0to1[7][2] = 0.664513627228086;
   fWeightMatrix0to1[8][2] = 0.737881605707793;
   fWeightMatrix0to1[9][2] = 1.43053177607618;
   fWeightMatrix0to1[10][2] = 1.81127345101158;
   fWeightMatrix0to1[11][2] = 1.69571600877624;
   fWeightMatrix0to1[12][2] = -0.708126767942012;
   fWeightMatrix0to1[13][2] = -1.5229658714389;
   fWeightMatrix0to1[14][2] = 0.786425445858666;
   fWeightMatrix0to1[15][2] = -0.44213230985614;
   fWeightMatrix0to1[0][3] = 1.88024615596139;
   fWeightMatrix0to1[1][3] = 1.50004010932425;
   fWeightMatrix0to1[2][3] = 0.982990517331068;
   fWeightMatrix0to1[3][3] = 1.17745695437063;
   fWeightMatrix0to1[4][3] = -1.73601163729192;
   fWeightMatrix0to1[5][3] = 0.552610357059501;
   fWeightMatrix0to1[6][3] = -1.72785135644919;
   fWeightMatrix0to1[7][3] = -0.606901942651035;
   fWeightMatrix0to1[8][3] = -0.727436017036756;
   fWeightMatrix0to1[9][3] = -1.24604937348539;
   fWeightMatrix0to1[10][3] = 1.45227542091195;
   fWeightMatrix0to1[11][3] = 1.14794573257364;
   fWeightMatrix0to1[12][3] = -1.5684564002029;
   fWeightMatrix0to1[13][3] = 0.370294303102253;
   fWeightMatrix0to1[14][3] = -0.612176233873785;
   fWeightMatrix0to1[15][3] = 0.195014792970722;
   fWeightMatrix0to1[0][4] = 2.24103360943822;
   fWeightMatrix0to1[1][4] = -1.09173557593475;
   fWeightMatrix0to1[2][4] = -0.51131154498398;
   fWeightMatrix0to1[3][4] = -0.771504811208364;
   fWeightMatrix0to1[4][4] = 0.69078710059957;
   fWeightMatrix0to1[5][4] = -0.588916290854634;
   fWeightMatrix0to1[6][4] = -0.815963071052699;
   fWeightMatrix0to1[7][4] = -0.234594193915677;
   fWeightMatrix0to1[8][4] = 1.28891731256322;
   fWeightMatrix0to1[9][4] = 1.44097393041809;
   fWeightMatrix0to1[10][4] = 1.27860528591286;
   fWeightMatrix0to1[11][4] = 0.13600688306782;
   fWeightMatrix0to1[12][4] = -1.88880981297389;
   fWeightMatrix0to1[13][4] = -1.69497402274461;
   fWeightMatrix0to1[14][4] = 0.881792845602231;
   fWeightMatrix0to1[15][4] = 0.119957303408929;
   fWeightMatrix0to1[0][5] = 1.9934655550029;
   fWeightMatrix0to1[1][5] = 0.0213076543960874;
   fWeightMatrix0to1[2][5] = 0.45683713755531;
   fWeightMatrix0to1[3][5] = 0.0688538847873979;
   fWeightMatrix0to1[4][5] = -0.846249929564923;
   fWeightMatrix0to1[5][5] = 0.131653237262248;
   fWeightMatrix0to1[6][5] = 0.00729846157309119;
   fWeightMatrix0to1[7][5] = 0.47467736315088;
   fWeightMatrix0to1[8][5] = -1.48487523926406;
   fWeightMatrix0to1[9][5] = -0.47455736491219;
   fWeightMatrix0to1[10][5] = -0.264169175497785;
   fWeightMatrix0to1[11][5] = 0.0662583318623262;
   fWeightMatrix0to1[12][5] = 1.4199980522915;
   fWeightMatrix0to1[13][5] = -1.48094253676283;
   fWeightMatrix0to1[14][5] = 0.16413317859897;
   fWeightMatrix0to1[15][5] = 0.653460693823026;
   fWeightMatrix0to1[0][6] = -0.872031433300555;
   fWeightMatrix0to1[1][6] = -0.206456931653318;
   fWeightMatrix0to1[2][6] = -0.812875848725794;
   fWeightMatrix0to1[3][6] = 0.0973687456450036;
   fWeightMatrix0to1[4][6] = -1.829131978421;
   fWeightMatrix0to1[5][6] = -0.409094131075873;
   fWeightMatrix0to1[6][6] = -0.103011051072804;
   fWeightMatrix0to1[7][6] = -0.122606907212297;
   fWeightMatrix0to1[8][6] = -3.11409708313399;
   fWeightMatrix0to1[9][6] = 0.053038815289357;
   fWeightMatrix0to1[10][6] = -0.980810821506576;
   fWeightMatrix0to1[11][6] = -0.688201606573822;
   fWeightMatrix0to1[12][6] = 0.676834764722677;
   fWeightMatrix0to1[13][6] = -0.498034727603564;
   fWeightMatrix0to1[14][6] = 0.251005802532561;
   fWeightMatrix0to1[15][6] = -0.398775135097001;
   fWeightMatrix0to1[0][7] = 0.499491475711629;
   fWeightMatrix0to1[1][7] = 3.89309050469041;
   fWeightMatrix0to1[2][7] = -1.03698754964345;
   fWeightMatrix0to1[3][7] = 4.43179828327959;
   fWeightMatrix0to1[4][7] = 0.570607654090662;
   fWeightMatrix0to1[5][7] = -5.678680984928;
   fWeightMatrix0to1[6][7] = -0.20129881701396;
   fWeightMatrix0to1[7][7] = -4.16590632420494;
   fWeightMatrix0to1[8][7] = -2.83948265566152;
   fWeightMatrix0to1[9][7] = 0.240015484323942;
   fWeightMatrix0to1[10][7] = -0.351960570190706;
   fWeightMatrix0to1[11][7] = 1.58837711217205;
   fWeightMatrix0to1[12][7] = 0.814975485818647;
   fWeightMatrix0to1[13][7] = -0.714783676786184;
   fWeightMatrix0to1[14][7] = -1.10386762242393;
   fWeightMatrix0to1[15][7] = 0.00921501780517443;
   fWeightMatrix0to1[0][8] = -1.452003845714;
   fWeightMatrix0to1[1][8] = 0.79466275887319;
   fWeightMatrix0to1[2][8] = -0.411991090021762;
   fWeightMatrix0to1[3][8] = -2.01151288099917;
   fWeightMatrix0to1[4][8] = 0.575862767523633;
   fWeightMatrix0to1[5][8] = -1.87975568869793;
   fWeightMatrix0to1[6][8] = -0.109956535940178;
   fWeightMatrix0to1[7][8] = 1.65770254582191;
   fWeightMatrix0to1[8][8] = 1.50226043469267;
   fWeightMatrix0to1[9][8] = -1.35782432435268;
   fWeightMatrix0to1[10][8] = 0.288124031645687;
   fWeightMatrix0to1[11][8] = 1.97466829907495;
   fWeightMatrix0to1[12][8] = 1.65172078080278;
   fWeightMatrix0to1[13][8] = 0.289094618513182;
   fWeightMatrix0to1[14][8] = -1.29344700875754;
   fWeightMatrix0to1[15][8] = -0.585811888672269;
   fWeightMatrix0to1[0][9] = -1.37813077516905;
   fWeightMatrix0to1[1][9] = 2.81388246232511;
   fWeightMatrix0to1[2][9] = 1.23160983216542;
   fWeightMatrix0to1[3][9] = -4.54895388439619;
   fWeightMatrix0to1[4][9] = -0.50657070421872;
   fWeightMatrix0to1[5][9] = -2.15488807125492;
   fWeightMatrix0to1[6][9] = -2.41792112425318;
   fWeightMatrix0to1[7][9] = 1.76044839552346;
   fWeightMatrix0to1[8][9] = 1.76613754884971;
   fWeightMatrix0to1[9][9] = -0.531446475328125;
   fWeightMatrix0to1[10][9] = -0.628476035564354;
   fWeightMatrix0to1[11][9] = -0.189357886352752;
   fWeightMatrix0to1[12][9] = 1.45968645679384;
   fWeightMatrix0to1[13][9] = -0.108171929750485;
   fWeightMatrix0to1[14][9] = 5.07323092896369;
   fWeightMatrix0to1[15][9] = -2.25511744593135;
   fWeightMatrix0to1[0][10] = 1.37454288162591;
   fWeightMatrix0to1[1][10] = -0.649338249734779;
   fWeightMatrix0to1[2][10] = -0.386440934371566;
   fWeightMatrix0to1[3][10] = 1.84048280560248;
   fWeightMatrix0to1[4][10] = 0.957117386420113;
   fWeightMatrix0to1[5][10] = 0.869696082874087;
   fWeightMatrix0to1[6][10] = 0.999104492057037;
   fWeightMatrix0to1[7][10] = 2.32035645283513;
   fWeightMatrix0to1[8][10] = -0.638203376286562;
   fWeightMatrix0to1[9][10] = 0.151592491519377;
   fWeightMatrix0to1[10][10] = 1.64299643207741;
   fWeightMatrix0to1[11][10] = 0.497679665360888;
   fWeightMatrix0to1[12][10] = -0.10684921947504;
   fWeightMatrix0to1[13][10] = 1.59628618940184;
   fWeightMatrix0to1[14][10] = 2.564598660199;
   fWeightMatrix0to1[15][10] = -2.4167665226766;
   fWeightMatrix0to1[0][11] = 0.582932097248923;
   fWeightMatrix0to1[1][11] = 0.173490527132223;
   fWeightMatrix0to1[2][11] = -0.151490694779322;
   fWeightMatrix0to1[3][11] = -1.74865192983133;
   fWeightMatrix0to1[4][11] = -1.58092326448265;
   fWeightMatrix0to1[5][11] = 0.0343938465922039;
   fWeightMatrix0to1[6][11] = 1.78974695271918;
   fWeightMatrix0to1[7][11] = -2.94055310164918;
   fWeightMatrix0to1[8][11] = -0.376842934445419;
   fWeightMatrix0to1[9][11] = -0.287144555870664;
   fWeightMatrix0to1[10][11] = 0.310573013937089;
   fWeightMatrix0to1[11][11] = 2.03455984755105;
   fWeightMatrix0to1[12][11] = -0.405329817861725;
   fWeightMatrix0to1[13][11] = -0.243119470811219;
   fWeightMatrix0to1[14][11] = -0.561455534411865;
   fWeightMatrix0to1[15][11] = 0.591561720235529;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.34662362125451;
   fWeightMatrix1to2[0][1] = 0.289938222900794;
   fWeightMatrix1to2[0][2] = 0.156329839200522;
   fWeightMatrix1to2[0][3] = -0.322994899924387;
   fWeightMatrix1to2[0][4] = -1.96994410435445;
   fWeightMatrix1to2[0][5] = -0.206011023949196;
   fWeightMatrix1to2[0][6] = 0.328797691387283;
   fWeightMatrix1to2[0][7] = -0.269800545818377;
   fWeightMatrix1to2[0][8] = -0.196310231124292;
   fWeightMatrix1to2[0][9] = 0.0342733430254818;
   fWeightMatrix1to2[0][10] = 0.121886483433012;
   fWeightMatrix1to2[0][11] = -1.55387532231717;
   fWeightMatrix1to2[0][12] = 1.47159505035232;
   fWeightMatrix1to2[0][13] = 0.326438815207414;
   fWeightMatrix1to2[0][14] = 0.603101284796486;
   fWeightMatrix1to2[0][15] = 0.347740997630309;
   fWeightMatrix1to2[0][16] = 0.329528690715728;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -99;
   fMax_1[0][0] = 0.998964726925;
   fMin_1[1][0] = -99;
   fMax_1[1][0] = 0.999695241451;
   fMin_1[2][0] = -99;
   fMax_1[2][0] = 0.999695241451;
   fMin_1[0][1] = -99;
   fMax_1[0][1] = 0.999956786633;
   fMin_1[1][1] = -99;
   fMax_1[1][1] = 0.999882161617;
   fMin_1[2][1] = -99;
   fMax_1[2][1] = 0.999956786633;
   fMin_1[0][2] = -99;
   fMax_1[0][2] = 0.999560713768;
   fMin_1[1][2] = -99;
   fMax_1[1][2] = 0.999614596367;
   fMin_1[2][2] = -99;
   fMax_1[2][2] = 0.999614596367;
   fMin_1[0][3] = -99;
   fMax_1[0][3] = 3.14135980606;
   fMin_1[1][3] = -99;
   fMax_1[1][3] = 3.1414334774;
   fMin_1[2][3] = -99;
   fMax_1[2][3] = 3.1414334774;
   fMin_1[0][4] = -99;
   fMax_1[0][4] = 3.14026069641;
   fMin_1[1][4] = -99;
   fMax_1[1][4] = 3.13832426071;
   fMin_1[2][4] = -99;
   fMax_1[2][4] = 3.14026069641;
   fMin_1[0][5] = 40.8050003052;
   fMax_1[0][5] = 117.858093262;
   fMin_1[1][5] = 40.3993835449;
   fMax_1[1][5] = 113.862014771;
   fMin_1[2][5] = 40.3993835449;
   fMax_1[2][5] = 117.858093262;
   fMin_1[0][6] = 12.0253534317;
   fMax_1[0][6] = 114.000205994;
   fMin_1[1][6] = 12.0306968689;
   fMax_1[1][6] = 108.812988281;
   fMin_1[2][6] = 12.0253534317;
   fMax_1[2][6] = 114.000205994;
   fMin_1[0][7] = -99;
   fMax_1[0][7] = 822.938476562;
   fMin_1[1][7] = -99;
   fMax_1[1][7] = 575.262817383;
   fMin_1[2][7] = -99;
   fMax_1[2][7] = 822.938476562;
   fMin_1[0][8] = -99;
   fMax_1[0][8] = 5.986951828;
   fMin_1[1][8] = -99;
   fMax_1[1][8] = 6.83502864838;
   fMin_1[2][8] = -99;
   fMax_1[2][8] = 6.83502864838;
   fMin_1[0][9] = -999;
   fMax_1[0][9] = 4060.77124023;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 2549.00561523;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 4060.77124023;
   fMin_1[0][10] = -999;
   fMax_1[0][10] = 8.83846282959;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 7.09231567383;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 8.83846282959;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
