// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 11:36:06 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 10000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar          f_angle_costhetastar                                            'F'    [-99,0.999695241451]
f_angle_costheta1             f_angle_costheta1             f_angle_costheta1             f_angle_costheta1                                               'F'    [-99,0.999956786633]
f_angle_costheta2             f_angle_costheta2             f_angle_costheta2             f_angle_costheta2                                               'F'    [-99,0.999614596367]
f_angle_phi                   f_angle_phi                   f_angle_phi                   f_angle_phi                                                     'F'    [-99,3.1414334774]
f_angle_phistar1              f_angle_phistar1              f_angle_phistar1              f_angle_phistar1                                                'F'    [-99,3.14026069641]
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.3993835449,117.858093262]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0253534317,114.000205994]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_angle_costhetastar", "f_angle_costheta1", "f_angle_costheta2", "f_angle_phi", "f_angle_phistar1", "f_Z1mass", "f_Z2mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -99;
      fVmax[0] = 0.999695241451263;
      fVmin[1] = -99;
      fVmax[1] = 0.999956786632538;
      fVmin[2] = -99;
      fVmax[2] = 0.999614596366882;
      fVmin[3] = -99;
      fVmax[3] = 3.14143347740173;
      fVmin[4] = -99;
      fVmax[4] = 3.14026069641113;
      fVmin[5] = 40.3993835449219;
      fVmax[5] = 117.858093261719;
      fVmin[6] = 12.0253534317017;
      fVmax[6] = 114.000205993652;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=0.244127967;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[6]<50.87291718)) rval+=-0.01130956302;   // importance = 0.010
   if ((inputValues[6]<46.01697159)) rval+=-0.01027505845;   // importance = 0.009
   if ((21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.01080969874;   // importance = 0.009
   if ((-1.725405455<inputValues[4])&&(inputValues[6]<60.58480835)) rval+=-0.009686101532;   // importance = 0.009
   if ((inputValues[6]<41.161026)) rval+=-0.00885531381;   // importance = 0.009
   if ((26.88742065<inputValues[6])&&(inputValues[6]<60.58480835)) rval+=-0.008994503198;   // importance = 0.009
   if ((80.97299194<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.008625051497;   // importance = 0.008
   if ((73.59597015<inputValues[5])&&(22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.009429265111;   // importance = 0.008
   if ((-1.722444296<inputValues[3])) rval+=-0.009737173731;   // importance = 0.008
   if ((22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.01066685061;   // importance = 0.008
   if ((inputValues[6]<60.58480835)) rval+=-0.01249096743;   // importance = 0.008
   if ((-1.725838304<inputValues[4])&&(21.9333992<inputValues[6])) rval+=-0.008535230616;   // importance = 0.008
   if ((26.59318924<inputValues[6])) rval+=-0.009268415611;   // importance = 0.008
   if ((21.15760422<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.01091610746;   // importance = 0.008
   if ((21.9333992<inputValues[6])) rval+=-0.01092261811;   // importance = 0.007
   if ((30.52165794<inputValues[6])) rval+=-0.007834924586;   // importance = 0.007
   if ((21.73724365<inputValues[6])) rval+=-0.01099856934;   // importance = 0.007
   if ((77.28448486<inputValues[5])) rval+=-0.01083613584;   // importance = 0.007
   if ((31.44913483<inputValues[6])) rval+=-0.007473611795;   // importance = 0.007
   if ((21.9333992<inputValues[6])&&(inputValues[6]<40.80666733)) rval+=-0.006990743101;   // importance = 0.007
   if ((88.35001373<inputValues[5])) rval+=-0.006997654502;   // importance = 0.007
   if ((17.5702877<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.01161875423;   // importance = 0.007
   if ((inputValues[5]<89.12621307)&&(inputValues[6]<80.0085907)) rval+=-0.006368931869;   // importance = 0.006
   if ((inputValues[4]<0.1581669748)&&(inputValues[6]<60.58480835)) rval+=-0.006282475729;   // importance = 0.006
   if ((89.12621307<inputValues[5])&&(inputValues[6]<80.0085907)) rval+=-0.006192174245;   // importance = 0.006
   if ((0.1581669748<inputValues[4])&&(inputValues[6]<60.58480835)) rval+=-0.006208491704;   // importance = 0.006
   if ((88.35001373<inputValues[5])&&(21.73724365<inputValues[6])) rval+=-0.005998571368;   // importance = 0.006
   if ((-0.2381126136<inputValues[0])&&(73.59597015<inputValues[5])&&(22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.005960076134;   // importance = 0.006
   if ((-0.1400423944<inputValues[4])&&(21.73724365<inputValues[6])) rval+=-0.005923130417;   // importance = 0.006
   if ((-0.7472797036<inputValues[3])&&(80.97299194<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.005873398195;   // importance = 0.006
   if ((14.6568327<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.01216452859;   // importance = 0.006
   if ((inputValues[5]<88.35001373)) rval+=-0.005702270757;   // importance = 0.006
   if ((-1.725405455<inputValues[4])&&(inputValues[4]<1.285570264)&&(inputValues[6]<60.58480835)) rval+=-0.005557783884;   // importance = 0.005
   if ((-1.725838304<inputValues[4])&&(inputValues[4]<1.516861558)&&(21.9333992<inputValues[6])) rval+=-0.005465354163;   // importance = 0.005
   if ((-0.2381126136<inputValues[0])&&(-0.7129861116<inputValues[1])&&(73.59597015<inputValues[5])&&(22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.005362661104;   // importance = 0.005
   if ((inputValues[6]<31.44913483)) rval+=-0.005226313465;   // importance = 0.005
   if ((inputValues[4]<-0.1400423944)&&(21.73724365<inputValues[6])) rval+=-0.005075438924;   // importance = 0.005
   if ((inputValues[5]<88.35001373)&&(21.73724365<inputValues[6])) rval+=-0.004999997973;   // importance = 0.005
   if ((inputValues[1]<0.4286642373)&&(88.35001373<inputValues[5])&&(21.73724365<inputValues[6])) rval+=-0.00451741223;   // importance = 0.004
   if ((inputValues[6]<80.0085907)) rval+=-0.01256110611;   // importance = 0.004
   if ((41.161026<inputValues[6])) rval+=-0.00384461145;   // importance = 0.004
   if ((inputValues[1]<0.4286642373)&&(88.35001373<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<50.77446365)) rval+=-0.004103967315;   // importance = 0.004
   if ((inputValues[5]<88.50453186)&&(31.44913483<inputValues[6])) rval+=-0.003878227023;   // importance = 0.004
   if ((88.50453186<inputValues[5])&&(31.44913483<inputValues[6])) rval+=-0.003595384772;   // importance = 0.003
   if ((inputValues[5]<88.35001373)&&(inputValues[6]<41.161026)) rval+=-0.003671999896;   // importance = 0.003
   if ((inputValues[0]<-0.2381126136)&&(73.59597015<inputValues[5])&&(22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.003469188977;   // importance = 0.003
   if ((-0.2379721403<inputValues[1])&&(-0.7472797036<inputValues[3])&&(80.97299194<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.003555687308;   // importance = 0.003
   if ((inputValues[6]<26.59318924)) rval+=-0.003431509648;   // importance = 0.003
   if ((88.50453186<inputValues[5])&&(inputValues[6]<31.44913483)) rval+=-0.003216991739;   // importance = 0.003
   if ((-0.1420332938<inputValues[2])&&(-1.725405455<inputValues[4])&&(inputValues[4]<1.285570264)&&(inputValues[6]<60.58480835)) rval+=-0.003065172128;   // importance = 0.003
   if ((26.59318924<inputValues[6])&&(inputValues[6]<34.92333984)) rval+=-0.003210475265;   // importance = 0.003
   if ((inputValues[1]<-0.3331638873)&&(inputValues[3]<1.288281441)) rval+=-0.002991138419;   // importance = 0.003
   if ((inputValues[3]<-1.722444296)) rval+=-0.002962751528;   // importance = 0.002
   if ((inputValues[3]<-0.7472797036)&&(80.97299194<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.002751653302;   // importance = 0.002
   if ((inputValues[4]<-1.725405455)&&(inputValues[6]<60.58480835)) rval+=-0.002804865901;   // importance = 0.002
   if ((46.01697159<inputValues[6])) rval+=-0.002424866809;   // importance = 0.002
   if ((-0.809658885<inputValues[0])&&(inputValues[0]<-0.2381126136)&&(73.59597015<inputValues[5])&&(22.59203148<inputValues[6])&&(inputValues[6]<80.0085907)) rval+=-0.002601219053;   // importance = 0.002
   if ((81.49880981<inputValues[5])&&(inputValues[5]<88.35001373)&&(21.73724365<inputValues[6])) rval+=-0.002589558018;   // importance = 0.002
   if ((46.70700073<inputValues[6])) rval+=-0.002232231914;   // importance = 0.002
   if ((inputValues[4]<-1.725838304)&&(21.9333992<inputValues[6])) rval+=-0.002387387493;   // importance = 0.002
   if ((inputValues[2]<-0.1420332938)&&(-1.725405455<inputValues[4])&&(inputValues[4]<1.285570264)&&(inputValues[6]<60.58480835)) rval+=-0.002492611756;   // importance = 0.002
   if ((inputValues[1]<-0.2379721403)&&(-0.7472797036<inputValues[3])&&(80.97299194<inputValues[5])&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.002317710887;   // importance = 0.002
   if ((inputValues[5]<88.35001373)&&(41.161026<inputValues[6])) rval+=-0.002030270861;   // importance = 0.002
   if ((inputValues[5]<80.97299194)&&(21.73724365<inputValues[6])&&(inputValues[6]<61.28125381)) rval+=-0.002184647246;   // importance = 0.002
   if ((46.70700073<inputValues[6])&&(inputValues[6]<60.58480835)) rval+=-0.002023274088;   // importance = 0.002
   if ((inputValues[5]<91.18141937)&&(26.59318924<inputValues[6])&&(inputValues[6]<34.92333984)) rval+=-0.002139903687;   // importance = 0.002
   if ((91.18141937<inputValues[5])&&(26.59318924<inputValues[6])&&(inputValues[6]<49.00494003)) rval+=-0.002090732232;   // importance = 0.001
   if ((inputValues[5]<88.50453186)&&(inputValues[6]<31.44913483)) rval+=-0.002009321725;   // importance = 0.001
   if ((-0.3331638873<inputValues[1])&&(inputValues[3]<-1.722444296)) rval+=-0.001872463696;   // importance = 0.001
   if ((inputValues[5]<77.28448486)) rval+=-0.001863789415;   // importance = 0.001
   if ((50.87291718<inputValues[6])) rval+=-0.00139036224;   // importance = 0.001
   if ((inputValues[6]<21.73724365)) rval+=-0.001701355919;   // importance = 0.001
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.0002465889931*std::min( double(2.948940277), std::max( double(inputValues[4]), double(-3.011342764)));   // importance = 0.001
   rval+=-0.05297036932*std::min( double(96.54495239), std::max( double(inputValues[5]), double(60.73322678)));   // importance = 1.000
   rval+=-0.01074055968*std::min( double(81.60360718), std::max( double(inputValues[6]), double(14.12879562)));   // importance = 0.408
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
