// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 14:15:25 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 3431
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.8473739624,117.858093262]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0253534317,114.000205994]
f_pt4l                        f_pt4l                        f_pt4l                        f_pt4l                                                          'F'    [-99,822.938476562]
f_massjj                      f_massjj                      f_massjj                      f_massjj                                                        'F'    [27.9619979858,4060.77124023]
f_deltajj                     f_deltajj                     f_deltajj                     f_deltajj                                                       'F'    [0.00819897651672,8.83846282959]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_Z1mass", "f_Z2mass", "f_pt4l", "f_massjj", "f_deltajj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.436338644804332;
   fWeightMatrix0to1[1][0] = 1.45548514923768;
   fWeightMatrix0to1[2][0] = 0.588697845833489;
   fWeightMatrix0to1[3][0] = 0.539684794289986;
   fWeightMatrix0to1[4][0] = -2.45007353802194;
   fWeightMatrix0to1[5][0] = 0.178290784786094;
   fWeightMatrix0to1[6][0] = -0.502629103023855;
   fWeightMatrix0to1[7][0] = 1.70893790082133;
   fWeightMatrix0to1[8][0] = -1.31577110599713;
   fWeightMatrix0to1[9][0] = -1.05047402204988;
   fWeightMatrix0to1[0][1] = -0.564320666394441;
   fWeightMatrix0to1[1][1] = 0.467218926671451;
   fWeightMatrix0to1[2][1] = -0.824183788293174;
   fWeightMatrix0to1[3][1] = 0.0721245440018013;
   fWeightMatrix0to1[4][1] = -0.642041450000238;
   fWeightMatrix0to1[5][1] = -0.461083178098426;
   fWeightMatrix0to1[6][1] = -0.187044210332804;
   fWeightMatrix0to1[7][1] = 1.63017779934703;
   fWeightMatrix0to1[8][1] = 0.774847503634773;
   fWeightMatrix0to1[9][1] = 0.476105850765194;
   fWeightMatrix0to1[0][2] = 0.00450098019433215;
   fWeightMatrix0to1[1][2] = -0.441187231029132;
   fWeightMatrix0to1[2][2] = 0.371604120516028;
   fWeightMatrix0to1[3][2] = 1.10017505911982;
   fWeightMatrix0to1[4][2] = -0.923396938366409;
   fWeightMatrix0to1[5][2] = -0.786742474642533;
   fWeightMatrix0to1[6][2] = 1.13225062579084;
   fWeightMatrix0to1[7][2] = -0.502467070634375;
   fWeightMatrix0to1[8][2] = -2.49460615067218;
   fWeightMatrix0to1[9][2] = -0.333409674996778;
   fWeightMatrix0to1[0][3] = 0.676489717880811;
   fWeightMatrix0to1[1][3] = 2.11786510536671;
   fWeightMatrix0to1[2][3] = -1.12909695998;
   fWeightMatrix0to1[3][3] = 0.253303802560123;
   fWeightMatrix0to1[4][3] = 0.0980117589538208;
   fWeightMatrix0to1[5][3] = -1.05090836636724;
   fWeightMatrix0to1[6][3] = -1.7929809900929;
   fWeightMatrix0to1[7][3] = 1.05928185165958;
   fWeightMatrix0to1[8][3] = -1.16363952953531;
   fWeightMatrix0to1[9][3] = 0.106611127651262;
   fWeightMatrix0to1[0][4] = 0.23696279870777;
   fWeightMatrix0to1[1][4] = 0.175833538645686;
   fWeightMatrix0to1[2][4] = 0.976563864501443;
   fWeightMatrix0to1[3][4] = 0.884761632631976;
   fWeightMatrix0to1[4][4] = -0.447277629472696;
   fWeightMatrix0to1[5][4] = -1.95342169089062;
   fWeightMatrix0to1[6][4] = 0.630608975685835;
   fWeightMatrix0to1[7][4] = -0.44544058536679;
   fWeightMatrix0to1[8][4] = 0.719549819367769;
   fWeightMatrix0to1[9][4] = 0.703255227045856;
   fWeightMatrix0to1[0][5] = 0.389811305829161;
   fWeightMatrix0to1[1][5] = 1.53927408371637;
   fWeightMatrix0to1[2][5] = -1.03938977781759;
   fWeightMatrix0to1[3][5] = 1.23112107972794;
   fWeightMatrix0to1[4][5] = -1.42154831164261;
   fWeightMatrix0to1[5][5] = -2.66383386554223;
   fWeightMatrix0to1[6][5] = -0.704331705394103;
   fWeightMatrix0to1[7][5] = -2.54638089127763;
   fWeightMatrix0to1[8][5] = 0.873689662207554;
   fWeightMatrix0to1[9][5] = 1.14420749105179;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.178309920910311;
   fWeightMatrix1to2[0][1] = 0.18499622799194;
   fWeightMatrix1to2[0][2] = -0.0217213708118066;
   fWeightMatrix1to2[0][3] = -0.0515390448268397;
   fWeightMatrix1to2[0][4] = 0.26959770367061;
   fWeightMatrix1to2[0][5] = -0.577018810736958;
   fWeightMatrix1to2[0][6] = -0.133138347284618;
   fWeightMatrix1to2[0][7] = -0.628221607775122;
   fWeightMatrix1to2[0][8] = 0.470677664077915;
   fWeightMatrix1to2[0][9] = -0.505315956331845;
   fWeightMatrix1to2[0][10] = -0.185750822423102;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 42.9957351685;
   fMax_1[0][0] = 117.858093262;
   fMin_1[1][0] = 40.8473739624;
   fMax_1[1][0] = 100.198852539;
   fMin_1[2][0] = 40.8473739624;
   fMax_1[2][0] = 117.858093262;
   fMin_1[0][1] = 12.0253534317;
   fMax_1[0][1] = 114.000205994;
   fMin_1[1][1] = 12.0650653839;
   fMax_1[1][1] = 94.2735214233;
   fMin_1[2][1] = 12.0253534317;
   fMax_1[2][1] = 114.000205994;
   fMin_1[0][2] = -99;
   fMax_1[0][2] = 822.938476562;
   fMin_1[1][2] = -99;
   fMax_1[1][2] = 575.262817383;
   fMin_1[2][2] = -99;
   fMax_1[2][2] = 822.938476562;
   fMin_1[0][3] = 27.9619979858;
   fMax_1[0][3] = 4060.77124023;
   fMin_1[1][3] = 29.6799240112;
   fMax_1[1][3] = 2549.00561523;
   fMin_1[2][3] = 27.9619979858;
   fMax_1[2][3] = 4060.77124023;
   fMin_1[0][4] = 0.00819897651672;
   fMax_1[0][4] = 8.83846282959;
   fMin_1[1][4] = 0.0224189758301;
   fMax_1[1][4] = 7.09231567383;
   fMin_1[2][4] = 0.00819897651672;
   fMax_1[2][4] = 8.83846282959;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
