// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/05       [336389]
Creator        : jbochenek
Date           : Mon Apr 15 15:57:54 2013
Host           : Linux ubuntu 3.2.0-39-generic #62-Ubuntu SMP Wed Feb 27 22:05:17 UTC 2013 i686 i686 i386 GNU/Linux
Dir            : /mnt/hgfs/work/HZZ4l_2013/scripts
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
f_Z1mass                      f_Z1mass                      f_Z1mass                      f_Z1mass                                                        'F'    [40.3993835449,116.369628906]
f_Z2mass                      f_Z2mass                      f_Z2mass                      f_Z2mass                                                        'F'    [12.0306968689,108.812988281]
f_pt4l                        f_pt4l                        f_pt4l                        f_pt4l                                                          'F'    [-99,501.772857666]
f_eta4l                       f_eta4l                       f_eta4l                       f_eta4l                                                         'F'    [-99,6.83502864838]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "f_Z1mass", "f_Z2mass", "f_pt4l", "f_eta4l" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][4];
   double fMax_1[3][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[10][5];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][10];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 5; fWeights[0] = new double[5]; 
   fLayerSize[1] = 10; fWeights[1] = new double[10]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.152673690565691;
   fWeightMatrix0to1[1][0] = -0.120004628057878;
   fWeightMatrix0to1[2][0] = 0.211831175789938;
   fWeightMatrix0to1[3][0] = 0.97337331108887;
   fWeightMatrix0to1[4][0] = -1.53210653297655;
   fWeightMatrix0to1[5][0] = -0.324529125008057;
   fWeightMatrix0to1[6][0] = 0.234556656203322;
   fWeightMatrix0to1[7][0] = 0.582212123118439;
   fWeightMatrix0to1[8][0] = 1.14712645583378;
   fWeightMatrix0to1[0][1] = -0.0548754350570153;
   fWeightMatrix0to1[1][1] = 0.386318156496728;
   fWeightMatrix0to1[2][1] = -0.224891537088452;
   fWeightMatrix0to1[3][1] = -1.69531111835748;
   fWeightMatrix0to1[4][1] = -0.719332593453931;
   fWeightMatrix0to1[5][1] = -0.0374067650634981;
   fWeightMatrix0to1[6][1] = -0.396398935230285;
   fWeightMatrix0to1[7][1] = 1.2981493886338;
   fWeightMatrix0to1[8][1] = 3.29884299228902;
   fWeightMatrix0to1[0][2] = -1.05318806736699;
   fWeightMatrix0to1[1][2] = 6.21285772402444;
   fWeightMatrix0to1[2][2] = -0.647352095779362;
   fWeightMatrix0to1[3][2] = -0.459046941815247;
   fWeightMatrix0to1[4][2] = 0.242418477390308;
   fWeightMatrix0to1[5][2] = 1.72391225852122;
   fWeightMatrix0to1[6][2] = -0.826589403672787;
   fWeightMatrix0to1[7][2] = 0.913793307929046;
   fWeightMatrix0to1[8][2] = 0.840335807846941;
   fWeightMatrix0to1[0][3] = -0.206215197165282;
   fWeightMatrix0to1[1][3] = 0.0673403943569288;
   fWeightMatrix0to1[2][3] = 0.174563567657143;
   fWeightMatrix0to1[3][3] = -0.036525172299608;
   fWeightMatrix0to1[4][3] = 0.789207817252054;
   fWeightMatrix0to1[5][3] = -0.244397270694133;
   fWeightMatrix0to1[6][3] = -1.22314542192358;
   fWeightMatrix0to1[7][3] = 0.312773355742365;
   fWeightMatrix0to1[8][3] = 0.240549669890214;
   fWeightMatrix0to1[0][4] = -0.358703581603608;
   fWeightMatrix0to1[1][4] = 3.46568015687996;
   fWeightMatrix0to1[2][4] = -0.572643404019998;
   fWeightMatrix0to1[3][4] = 1.68332474596519;
   fWeightMatrix0to1[4][4] = 2.15537808177976;
   fWeightMatrix0to1[5][4] = 0.923100041820521;
   fWeightMatrix0to1[6][4] = 0.344744534215459;
   fWeightMatrix0to1[7][4] = 0.350661295304239;
   fWeightMatrix0to1[8][4] = 0.123410035537522;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.174110468596159;
   fWeightMatrix1to2[0][1] = 0.526293246699245;
   fWeightMatrix1to2[0][2] = -0.0143544327774389;
   fWeightMatrix1to2[0][3] = 1.08979305643235;
   fWeightMatrix1to2[0][4] = 0.720750608788941;
   fWeightMatrix1to2[0][5] = 0.0912854050432423;
   fWeightMatrix1to2[0][6] = 0.176149463971242;
   fWeightMatrix1to2[0][7] = -0.318903503611839;
   fWeightMatrix1to2[0][8] = 0.37580102760079;
   fWeightMatrix1to2[0][9] = -1.26349736429108;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 40.8050003052;
   fMax_1[0][0] = 116.369628906;
   fMin_1[1][0] = 40.3993835449;
   fMax_1[1][0] = 113.862014771;
   fMin_1[2][0] = 40.3993835449;
   fMax_1[2][0] = 116.369628906;
   fMin_1[0][1] = 12.1532917023;
   fMax_1[0][1] = 101.054237366;
   fMin_1[1][1] = 12.0306968689;
   fMax_1[1][1] = 108.812988281;
   fMin_1[2][1] = 12.0306968689;
   fMax_1[2][1] = 108.812988281;
   fMin_1[0][2] = -99;
   fMax_1[0][2] = 501.772857666;
   fMin_1[1][2] = -99;
   fMax_1[1][2] = 404.44644165;
   fMin_1[2][2] = -99;
   fMax_1[2][2] = 501.772857666;
   fMin_1[0][3] = -99;
   fMax_1[0][3] = 5.986951828;
   fMin_1[1][3] = -99;
   fMax_1[1][3] = 6.83502864838;
   fMin_1[2][3] = -99;
   fMax_1[2][3] = 6.83502864838;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 4;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<4;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
